### ISSUE TITLE
Empty Main Branch without Documentation or Code

### ISSUE THREAD

**Issue by ultra-hash** [MeghavatiChaudhari/SwiftCard#3]
I've noticed that the main branch of this project appears to be completely empty, lacking both documentation and code. As a potential user/contributor, I found this to be a bit confusing, and I believe it could be beneficial to provide some basic information or code in the main branch. This would help users understand the purpose of the project and how to get started more easily.

**Comment by MeghavatiChaudhari** [comment]
Yes, it is my first time that I made project open source.currently I am
also learning new things and open source.thank you so much for your
valuable information.
